#!usr/bin/env python2
import os
from re import search as s

spritelist = [] # list with filenames of usable files
# adding (case-indep) .png and .jpg files to spritelist
for filename in os.listdir('./sprites'):
  if filename[-4:].lower() == '.png' or\
    filename[-4:].lower() == '.jpg':
      spritelist.append(filename)

s2 = ''; s4 = ''; s6 = ''; s8 = '';
# defining 'sources' object, which holds relative paths+filenames to sourcefiles:
for filename in spritelist:
  s2 += "  {}: '{}',\n".\
    format( s('(\w+)_',filename).group(1), 'sprites/'+filename )
# defining 'frames' object, which holds the number of frames per file:
for filename in spritelist:
  s4 += "  {}: {},\n".\
    format( s('(\w+)_',filename).group(1), s('f=(\w+)_',filename).group(1) )
# defining 'width' object, which holds the width of each file:
for filename in spritelist:
  s6 += "  {}: {},\n".\
    format( s('(\w+)_',filename).group(1), s('w=(\w+)_',filename).group(1) )
# defining 'height' object, which holds the height of each file:
for filename in spritelist:
  s8 += "  {}: {},\n".\
    format( s('(\w+)_',filename).group(1), s('h=(\w+).',filename).group(1) ) 

s1 = '''// code generated by get_imagesnames.py\n\nvar images = {};    // container for the images
var sources = {  // sources of the images\n'''
s3 = '''\n};
var frames = {  // number of frames per image\n'''
s5 = '''\n};
var width = {  // width of the images\n'''
s7 = '''\n};
var height = {  // height of the images\n'''

s9 = '''};\n
for (var src in sources) {          // for all images that need to be added:
  images[src] = new Image();        // for every image, create an Image object
  images[src].src = sources[src];   // add source images to Image objects
  images[src].frames = frames[src]; // add source images to Image objects
  images[src].width = width[src];   // add source images to Image objects
  images[src].height = height[src]; // add source images to Image objects
};

console.log(sources)
console.log(images)'''

with open('loadImages.js', 'w') as output_file:
  output_file.write(s1+s2[:-2]+s3+s4[:-2]+s5+s6[:-2]+s7+s8+s9)