// code generated by get_imagesnames.py

var images = {};    // container for the images
var sources = {  // sources of the images
  capguybig: 'sprites/capguybig_f=8_w=1472_h=325.png',
  capguy: 'sprites/capguy_f=8_w=435_h=100.png',
  dango_blue_dieleft: 'sprites/dango_blue_dieleft_f=8_w=480_h=40.png',
  dango_blue_dieright: 'sprites/dango_blue_dieright_f=8_w=480_h=40.png',
  dango_blue_walkleft: 'sprites/dango_blue_walkleft_f=4_w=240_h=40.png',
  dango_blue_walkright: 'sprites/dango_blue_walkright_f=4_w=240_h=40.png',
  dango_green_walkleft: 'sprites/dango_green_walkleft_f=4_w=240_h=40.png',
  dango_green_walkright: 'sprites/dango_green_walkright_f=4_w=240_h=40.png',
  dango_lilac_walkleft: 'sprites/dango_lilac_walkleft_f=4_w=240_h=40.png',
  dango_lilac_walkright: 'sprites/dango_lilac_walkright_f=4_w=240_h=40.png',
  dango_orange_walkleft: 'sprites/dango_orange_walkleft_f=4_w=240_h=40.png',
  dango_orange_walkright: 'sprites/dango_orange_walkright_f=4_w=240_h=40.png',
  dango_red_walkleft: 'sprites/dango_red_walkleft_f=4_w=240_h=40.png',
  dango_red_walkright: 'sprites/dango_red_walkright_f=4_w=240_h=40.png',
  dango_yellow_walkleft: 'sprites/dango_yellow_walkleft_f=4_w=240_h=40.png',
  dango_yellow_walkright: 'sprites/dango_yellow_walkright_f=4_w=240_h=40.png',
  stickman: 'sprites/stickman_f=4_w=120_h=60.png',
  stolen: 'sprites/stolen_f=6_w=248_h=60.png',
  test1_fireball_left: 'sprites/test1_fireball_left_f=4_w=164_h=30.png',
  test1_fireball_right: 'sprites/test1_fireball_right_f=4_w=164_h=30.png',
  test1_jumping_left: 'sprites/test1_jumping_left_f=1_w=47_h=60.png',
  test1_jumping_right: 'sprites/test1_jumping_right_f=1_w=47_h=60.png',
  test1_running_left: 'sprites/test1_running_left_f=4_w=188_h=60.png',
  test1_running_right: 'sprites/test1_running_right_f=4_w=188_h=60.png',
  test1_standing_left: 'sprites/test1_standing_left_f=1_w=47_h=60.png',
  test1_standing_right: 'sprites/test1_standing_right_f=1_w=47_h=60.png'
};
var frames = {  // number of frames per image
  capguybig: 8,
  capguy: 8,
  dango_blue_dieleft: 8,
  dango_blue_dieright: 8,
  dango_blue_walkleft: 4,
  dango_blue_walkright: 4,
  dango_green_walkleft: 4,
  dango_green_walkright: 4,
  dango_lilac_walkleft: 4,
  dango_lilac_walkright: 4,
  dango_orange_walkleft: 4,
  dango_orange_walkright: 4,
  dango_red_walkleft: 4,
  dango_red_walkright: 4,
  dango_yellow_walkleft: 4,
  dango_yellow_walkright: 4,
  stickman: 4,
  stolen: 6,
  test1_fireball_left: 4,
  test1_fireball_right: 4,
  test1_jumping_left: 1,
  test1_jumping_right: 1,
  test1_running_left: 4,
  test1_running_right: 4,
  test1_standing_left: 1,
  test1_standing_right: 1
};
var width = {  // width of the images
  capguybig: 1472,
  capguy: 435,
  dango_blue_dieleft: 480,
  dango_blue_dieright: 480,
  dango_blue_walkleft: 240,
  dango_blue_walkright: 240,
  dango_green_walkleft: 240,
  dango_green_walkright: 240,
  dango_lilac_walkleft: 240,
  dango_lilac_walkright: 240,
  dango_orange_walkleft: 240,
  dango_orange_walkright: 240,
  dango_red_walkleft: 240,
  dango_red_walkright: 240,
  dango_yellow_walkleft: 240,
  dango_yellow_walkright: 240,
  stickman: 120,
  stolen: 248,
  test1_fireball_left: 164,
  test1_fireball_right: 164,
  test1_jumping_left: 47,
  test1_jumping_right: 47,
  test1_running_left: 188,
  test1_running_right: 188,
  test1_standing_left: 47,
  test1_standing_right: 47
};
var height = {  // height of the images
  capguybig: 325,
  capguy: 100,
  dango_blue_dieleft: 40,
  dango_blue_dieright: 40,
  dango_blue_walkleft: 40,
  dango_blue_walkright: 40,
  dango_green_walkleft: 40,
  dango_green_walkright: 40,
  dango_lilac_walkleft: 40,
  dango_lilac_walkright: 40,
  dango_orange_walkleft: 40,
  dango_orange_walkright: 40,
  dango_red_walkleft: 40,
  dango_red_walkright: 40,
  dango_yellow_walkleft: 40,
  dango_yellow_walkright: 40,
  stickman: 60,
  stolen: 60,
  test1_fireball_left: 30,
  test1_fireball_right: 30,
  test1_jumping_left: 60,
  test1_jumping_right: 60,
  test1_running_left: 60,
  test1_running_right: 60,
  test1_standing_left: 60,
  test1_standing_right: 60,
};

for (var src in sources) {          // for all images that need to be added:
  images[src] = new Image();        // for every image, create an Image object
  images[src].src = sources[src];   // add source images to Image objects
  images[src].frames = frames[src]; // add source images to Image objects
  images[src].width = width[src];   // add source images to Image objects
  images[src].height = height[src]; // add source images to Image objects
};

console.log(sources)
console.log(images)